export const Tertiary = [
  { title: "Chad" },
  { title: "Aru Village Residents" },
  { title: "Alexi" },
  { title: "Alexi's Father" },
  { title: "Johnny" },
  { title: "Johnny's Mother" },
  { title: "Little Flower" },
  { title: "Little Flower's Father" },
  { title: "Sarah" },
  { title: "Sarah's Mother" },
  { title: "Sarah's Father" },
  { title: "Emperor Pilaf's Mother" },
  { title: "Brown Country Cowboys" },
  { title: "Chibi" },
  { title: "Tall Man" },
  { title: "Tubs" },
  { title: "Muscular Lady" },
  { title: "Mermaid" },
  { title: "Milk Delivery Man" },
  { title: "Registration Staff Member" },
  { title: "Unnamed Tournament Staff Member" },
  { title: "Tournament Referee" },
  { title: "Elimation Round Competitors" },
  { title: "Fighter 40" },
  { title: "Fighter 69" },
  { title: "Fighter 83" },
  { title: "Fighter 97" },
  { title: "Great Lee" },
  { title: "Kickboxer" },
  { title: "Nam's Family" },
  { title: "Nam's Father" },
  { title: "Ami" },
  { title: "Dabu" },
  { title: "Four Professional Boxers" },
  { title: "Silver's Henchmen" },
  { title: "Muscle Tower Guards" },
  { title: "White's Scouts" },
  { title: "White's Binoculars Soldier" },
  { title: "Tank Soldiers" },
  { title: "Outdoor Guards" },
  { title: "Floor Guards" },
  { title: "Maze Soldiers" },
  { title: "General White's Sisters" },
  { title: "Mother with Sunglasses" },
  { title: "West City Taxi Driver" },
  { title: "Bulma (citizen)" },
  { title: "Unnamed Big Fighter" },
  { title: "Big Fighter's Friends" },
  { title: "Yamcha's Fan Club" },
  { title: "Nose-picking soldier" },
  { title: "Blue's Tiger soldier" },
  { title: "Crocodile soldier" },
  { title: "Turtle's son" },
  { title: "Scout 0-1" },
  { title: "Commander Red's Painter" },
  { title: "Mousey" },
  { title: "Soldier 23" },
  { title: "Samuel" },
  { title: "Tao's Tailor" },
  { title: "Sniper Assassin" },
  { title: "Violet's Henchmen" },
  { title: "Tailor Ford" },
  { title: "Rich Couple" },
  { title: "Mighty-but-compassionate Warrior" },
  { title: "Tiger Thief" },
  { title: "Unnamed Warrior" },
  { title: "Chenshi" },
  { title: "King Wonton and Queen Harumaki" },
  { title: "Princess Misa's Parents" },
  { title: "Mirror Demon" },
  { title: "Pinfu" },
  { title: "Unnamed Tiger" },
  { title: "Mohawked Fighter" },
  { title: "Sumo Wrestler" },
  { title: "Unnamed Fighter injured by Tien" },
  { title: "Strong King's Guard" },
  { title: "Piccolo's Adoptive Parents" },
  { title: "Tai" },
  { title: "Patrol 15" },
  { title: "Mr. Popo's Cat" },
  { title: "Chuu Lee's Family" },
  { title: "Chuu Lee's Mother" },
  { title: "Pippi" },
  { title: "Goku's Doll" },
  { title: "Cat Man" },
  { title: "Shen's Son" },
  { title: "Pansy's Parents" },
  { title: "Pansy's Father" },
  { title: "Pansy's Mother" },
  { title: "Fire Safety Kids' Parents" },
  { title: "Billy" },
  { title: "Murdock" },
  { title: "Tien's Mom" },
  { title: "Princess Snake's Attendants" },
  { title: "Scarface's grandmother" },
  { title: "Unnamed Doctor" },
  { title: "Emi" },
  { title: "Three Soldiers on Planet Frieza #79" },
  { title: "Planet Frieza 79 Control Man" },
  { title: "Appule's Race Control Tower Soldier" },
  { title: "Plant Frieza No. 79 Malaka's Race Doctor" },
  { title: "Nabana" },
  { title: "Krumbo" },
  { title: "Guprei" },
  { title: "Frog-Face" },
  { title: "Ginyu Force's Logistics Unit" },
  { title: "Strock" },
  { title: "Captain Strong" },
  { title: "Goose" },
  { title: "Oggers" },
  { title: "Unnamed Saiyan Messenger Soldier" },
  { title: "Zorn" },
  { title: "Gonma" },
  { title: "Litt Frieza Soldier" },
  { title: "Krillin and Maron's children" },
  { title: "Unnamed Captain" },
  { title: "King Cold's Malaka's Race Medic" },
  { title: "Future Android 19" },
  { title: "Cletus and Otis" },
  { title: "Paperclip Truck Driver" },
  { title: "Two punks" },
  { title: "Rex and Natalie" },
  { title: "Tommie" },
  { title: "Mack" },
  { title: "Lucky Foods workers" },
  { title: "Walter" },
  { title: "Future Trunks (Cell's timeline)" },
  { title: "Future Nappa" },
  { title: "Future Trunks (Unknown timeline)" },
  { title: "Barry Walters" },
  { title: "Beverly Jones" },
  { title: "John Johnson" },
  { title: "Marsha" },
  { title: "Capsule Corporation Explorer" },
  { title: "Lionel" },
  { title: "Parsley City Old Man" },
  { title: "Yamcha's Girlfriend" },
  { title: "Cell (Unseen timeline)" },
  { title: "Other World Fighter" },
  { title: "Duo of Robbers" },
  { title: "Miss Hamilton" },
  { title: "Jimbo and Slimjim" },
  { title: "Chad and Loretta" },
  { title: "Ed" },
  { title: "Nick Hornby" },
  { title: "Manager" },
  { title: "Marvin" },
  { title: "Actors in the Cell Games Reenactment" },
  { title: "K. Fujicka" },
  { title: "M. Hashimoto" },
  { title: "Koryuu" },
  { title: "Mooki" },
  { title: "Unnamed Asian Child" },
  { title: "Fred" },
  { title: "Young Girl" },
  { title: "Bongo the Rabbit" },
  { title: "Demetrious" },
  { title: "Unnamed Namekian Warrior" },
  { title: "Tony" },
  { title: "Machine Gunner" },
  { title: "Motorcycle Policewoman" },
  { title: "Sorbet's Bouncers" },
  { title: "Sorbet's Malaka's Race Medic" },
  { title: "Frieza Force Officer" },
  { title: "Make-up Store Man" },
  { title: "Snackian Ambassador and Secretary" },
  { title: "Beavis" },
  { title: "Jaco's Father" },
  { title: "Future Pui Pui" },
  { title: "Future Yakon" },
  { title: "Future Shenron" },
  { title: "Goku (Goku Black's timeline)" },
  { title: "Goten (Goku Black's timeline)" },
  { title: "Chi-Chi (Goku Black's timeline)" },
  { title: "Gowasu (Goku Black's timeline)" },
  { title: "Masked Poacher" },
  { title: "Poacher A" },
  { title: "Poacher B" },
  { title: "Caulifla's Gang Members" },
  { title: "Obni's Family" },
  { title: "Villainous Demon" },
  { title: "Moroko" },
  { title: "Male Frieza Soldiers" },
  { title: "Male Saiyans" },
  { title: "Male Saiyan Flight Staff" },
  { title: "Male Saiyan Guards" },
  { title: "Female Frieza Crew" },
  { title: "Male Frieza Crew" },
  { title: "Male Saiyan Generals" },
  { title: "Male Saiyan Control Tower" },
  { title: "Male Saiyan Staff" },
  { title: "Female Saiyan" },
  { title: "Male Saiyan Courtier" },
  { title: "Saiyan Army Snipers" },
  { title: "Tanissh" },
  { title: "Tsuburi" },
  { title: "Planet Namek Savior" },
  { title: "Vinesal" },
  { title: "Hatska" },
  { title: "Flayk" },
  { title: "Mr. Henderson" },
  { title: "Poperu" },
  { title: "Giant from Monmaasu" },
  { title: "Luud Cult Mercenary" },
  { title: "DNA Replicants" },
  { title: "Arcade Gangster" },
  { title: "Danny" },
  { title: "Charlie" },
  { title: "Mad Chilli" },
  { title: "Colm" },
  { title: "Gull" },
  { title: "Elderly Couple" },
  { title: "Unnamed Truck Driver" },
  { title: "Gokus" },
  { title: "Sachie-chan Guu!!" },
  { title: "Octo Messengers" },
  { title: "Sachie's friend" },
  { title: "Satoyama Junior High Teacher" },
  { title: "Yamada Haruo" },
  { title: "Beat's Mom" },
  { title: "Beat's Grandfather" },
  { title: "Froze's parents" },
  { title: "Moden" },
  { title: "Hero Stadium Announcer" },
  { title: "Roche" },
  { title: "Bocacchi" },
  { title: "Yuto" },
  { title: "Lody" },
  { title: "Chamile" },
  { title: "Mint" },
  { title: "Kang" },
  { title: "Kong" },
  { title: "Anne" },
  { title: "Nim's Mom" },
  { title: "Yuto's Mother" },
  { title: "Incha" },
  { title: "Maline" },
  { title: "Tour" },
  { title: "Battle Navigator Kaisei" },
  { title: "Mr. Satanman" },
  { title: "Super Hero Robo" },
  { title: "Lulu" },
  { title: "Moll" },
  { title: "Rill" },
  { title: "Zaus" },
  { title: "Bojack (Universe 6)" },
  { title: "Zangya (Universe 6)" },
  { title: "Bio-Broly (Universe 6)" },
  { title: "Paragus (Universe 6)" },
  { title: "Hirudegarn (Universe 6)" },
  { title: "Future Android 13" },
  { title: "Future Android 14" },
  { title: "Future Android 15" },
  { title: "Unseen Boy" },
  { title: "Vinnie" },
  { title: "Crook" },
  { title: "Teacher Plush" },
  { title: "Iko" },
  { title: "Murasaki family sons" },
  { title: "General White Jr." },
  { title: "Hank" },
  { title: "Mothman" },
  { title: "Mrs. Bon" },
  { title: "Bong Bong" },
  { title: "Captain Taylor" },
  { title: "Sora Kahn" },
  { title: "Baby Buu" },
  { title: "Majin Mani Mani" },
  { title: "Orlen's Father" },
  { title: "Sapphire" },
  { title: "Pearl" },
  { title: "Former Frieza Force Soldier (Appule's race)" },
  { title: "Despondent Man" },
  { title: "Ruhna" },
  { title: "Sapa" },
  { title: "Chapu" },
  { title: "Peruka" },
  { title: "Queen of the Saiyans" },
  { title: "Master of Satan Castle" },
  { title: "Android 17's Wife" },
];
